### ISSUE TITLE
Roadmap for 4.0.0

### ISSUE THREAD

**Issue by synw** [synw/sqlcool#12]
#### New features

- [x] Add informative getters to the schema
- [x] Join on multiple foreign keys
- [x] Database models: use a mixin to give any model methods to interact with the database
- [x] Foreign key support for database models

#### Tests, doc and examples

- [x] Test the new features
- [x] Examples for the new features
- [x] Document the new features
- [x] Refresh the documentation and add missing doc
- [x] Write more tests and increase the coverage
- [x] Better presentation for the example app homepage

## Database models

This release will introduce the database models feature: any model can use a `DbModel` mixin to get database crud methods: select, delete, insert, upsert. Some serializers must be written in the model: `fromDb` and `toDb`:

```dart
class Car with DbModel {
  Car({this.id,
       this.name,
       this.price,
       this.year});

  final String name;
  final double price;
  final DateTime year;

 @override
  int id;

@override
  Db get db => conf.db;

  @override
  DbTable get table => carTable;

  @override
  Map<String, dynamic> toDb() => <String, dynamic>{
        "name": name,
        "price": price,
        "year": year.millisecondsSinceEpoch
      };

  @override
  Car fromDb(Map<String, dynamic> map) => Car(
        id: map["id"] as int,
        name: map["name"].toString(),
        price: map["price"] as double,
        year: DateTime.fromMillisecondsSinceEpoch(map["year"] as int));
}

/// In schemas.dart declare the schema as usual

final carTable = DbTable("car")
          ..varchar("name")
          ..real("price")
          ..integer("year"));
  }

/// initialize the database with model schemas

final db = Db();
db.init(path: "mydb.sqlite", schema = <DbTable>[carTable]);
```

Use the model's crud methods to query the database:

```dart
/// car is an instance of Car
await car.sqlInsert();
await car.sqlUpdate();
await car.sqlUpsert();
await car.sqlDelete();
// select
final cars = List<Car>.from(await Car().sqlSelect(where: "price<25000"));
```

Check the [example](https://github.com/synw/sqlcool/tree/master/example/lib/pages/dbmodels) for foreign key support

This way no need to deal with maps decoding and encoding when doing database operations: all the data is of the model type
